#!/bin/bash -e

if [ "$(id -u)" != '0' ]; then
  devel-su "$0" "$1"
  exit 1
fi

size="${1:-1.75}"
echo "Will set size to $size."

echo "Installing the required packages."
pkcon install --allow-reinstall -y sailfish-content-graphics-{default,closed}-{z1.0,z1.25,z1.5,z1.75,z2.0}

echo "Updating the configuration."
# [desktop/sailfish/silica]
# theme_pixel_ratio=1.75
# theme_icon_subdir='z1.75'
sed -i "s/\(theme_pixel_ratio=\).*$/\1$size/g;s/\(theme_icon_subdir='z\).*$/\1$size'/g" /etc/dconf/db/vendor.d/silica-configs.txt

echo "Compiling stuff."
dconf compile /etc/dconf/db/vendor.new /etc/dconf/db/vendor.d

echo "Applying the new config."
cd /etc/dconf/db
mv vendor{,.bak}
mv vendor.new vendor

echo "Restarting lipstick. It will take several seconds. If it doesn't work, reboot."
for i in {10..1}; do
  echo -n "  $i"
  sleep 1
done
echo

systemctl --user restart lipstick
